djangoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('pizza/', include('pizza.urls')),
    path('studenci/', include('studenci.urls')),
    path('ankiety/', include('ankiety.urls')),
    path('admin/', admin.site.urls),
]

pizza/urls.py
from django.urls import path

from . import views
app_name = 'pizza'
urlpatterns = [
	path('', views.index, name='index'),
    path('news/', views.news, name='news'),
    path('skladnik/dodaj', views.SkladnikDodaj, name='skladnik_add'),

]

studenci/urls.py
from django.urls import path
from django.views.generic import ListView
from . import views
from studenci.models import Miasto

app_name = 'studenci'
urlpatterns = [
	path('', views.index, name='index'),
    path('miasta/lista', ListView.as_view(model=Miasto), name='miasta_lista'),
    path('news/', views.news, name='news'),
    path('miasta/', views.miasta, name='miasta'),
    path('miasta/dodaj', views.DodajMiasto.as_view(), name='miasta_dodaj'),
    path('miasta/edytuj/<int:pk>', views.EdytujMiasto.as_view(), name='miasta_edytuj'),
    path('miasta/usun/<int:pk>', views.UsunMiasto.as_view(), name='miasta_usun'),
    path('uczelnia/', views.uczelnia, name='uczelnia'),
    path('uczelnia/lista', views.ListaUczelni.as_view(), name='uczelnie_lista'),
    path('uczelnia/dodaj', views.DodajUczelnia.as_view(), name='uczelnia_dodaj'),
    path('uczelnia/edytuj/<int:pk>', views.EdytujUczelnia.as_view(), name='uczelnia_edytuj'),
    path('uczelnia/usun/<int:pk>', views.UsunUczelnia.as_view(), name='uczelnia_usun'),
    path('login/', views.login, name='login'),
    path('login2/', views.login2, name='login2'),

]

studenci/models.py
from django.db import models


class Miasto(models.Model):
    nazwa = models.CharField(
        verbose_name='miasto',
        max_length=30,
        help_text='Nazwa miasta')
    kod = models.CharField(
        max_length=6,
        help_text='Kod pocztowy')

    def __str__(self):
        return self.nazwa;

    class Meta:
        verbose_name_plural = "miasta"

class Uczelnia(models.Model):
    nazwa = models.CharField(
        verbose_name='uczelnia',
        max_length=30,
        help_text='Nazwa uczelni')

    def __str__(self):
        return self.nazwa;

    class Meta:
        verbose_name_plural = "uczelnie"

class Student(models.Model):
    imie = models.CharField('imię', max_length=30)
    nazwisko = models.CharField(max_length=30)
    uczelnia = models.ForeignKey(Uczelnia, on_delete=models.SET_NULL, null=True)
    miasto = models.ForeignKey(Miasto, on_delete=models.SET_NULL, null=True)
    roks = models.CharField('rok studiów', max_length=3)
    dochod = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.imie + " " + self.nazwisko;

    class Meta:
        verbose_name_plural = "studenci"

studenci/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from studenci.models import Miasto, Uczelnia
from django.contrib import messages
from studenci.form import StudentLoginForm, MiastoModelForm
from studenci.form import UczelniaForm, MiastoForm
from django.urls import reverse
from django.views.generic import ListView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin


def index(request):
    #return HttpResponse("Witaj w aplikacji Studenci!")
    return render(request, 'studenci/index.html')


def news(request):
    #return HttpResponse("<h1>Nowości u studentów</h1>")
    return render(request, 'pizza/news.html')

def miasta(request):

    if request.method == 'POST':
        #nazwa= request.POST.get('nazwa')
        #kod= request.POST.get('kod')
        form = MiastoForm(request.POST)
        if form.is_valid():
            m = Miasto(nazwa=form.cleaned_data['nazwa'], kod=form.cleaned_data['kod'])
            m.save()
            messages.success(request, "Dane zapisano!")
        else:
            messages.error(request, "Błędne dane deb***!")
    else:
        form = MiastoForm()

    miasta = Miasto.objects.all()
    kontekst = {
        'form': form,
        'miasta': miasta
    }
    return render(request, 'studenci/miasta.html', kontekst)


def uczelnia(request):

    if request.method == 'POST':
        form = UczelniaForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            u = Uczelnia(nazwa=form.cleaned_data['nazwa'])
            u.save()
            messages.success(request, "Dane zapisano!")
            # przekierowanie

            return redirect(reverse('studenci:uczelnia'))
    else:
        form = UczelniaForm()

    uczelnia = Uczelnia.objects.all()
    kontekst = {
        'form': form,
        'uczelnia': uczelnia
    }

    if request.user.has_perm('studenci.add_uczelnia'):
        return render(request, 'studenci/uczelnia.html', kontekst)
    else:
        messages.info(request, "Nie możesz dodawać uczelni!!")
        return redirect(reverse('studenci:index'))
def login(request):

    if request.method == 'POST':
        nazwa= request.POST.get('nazwa')
        kod= request.POST.get('kod')
        if len(nazwa.strip()):
            m = Miasto(nazwa=nazwa, kod=kod)
            m.save()
            messages.success(request, "Dane zapisano!")
        else:
            messages.error(request, "Błędne dane!")
    else:
        form = StudentLoginForm()


    kontekst = { 'form': form }
    return render(request, 'studenci/login.html', kontekst)

def login2(request):

    if request.method == 'POST':
        nazwa= request.POST.get('nazwa')
        kod= request.POST.get('kod')
        if len(nazwa.strip()):
            m = Miasto(nazwa=nazwa, kod=kod)
            m.save()
            messages.success(request, "Dane zapisano!")
        else:
            messages.error(request, "Błędne dane!")
    else:
        form = UczelniaForm()


    kontekst = { 'form': form }
    return render(request, 'studenci/login2.html', kontekst)

class ListaUczelni(ListView):
    model = Uczelnia
    context_object_name = 'uczelnia'
    template_name = 'studenci/lista_uczelni.html'

@method_decorator(login_required, name='dispatch')
class DodajMiasto(CreateView):
    model = Miasto
    fields = ('nazwa', 'kod')
    template_name = 'studenci/miasto_dodaj.html'
    success_url = reverse_lazy('studenci:miasta_lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['miasta'] = Miasto.objects.all()
        return context

    def form_valid(self, form):
        messages.success(self.request, "Dodano miasto!")
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class DodajUczelnia(CreateView):
    model = Uczelnia
    fields = ('nazwa',)
    template_name = 'studenci/uczelnia_dodaj.html'
    success_url = reverse_lazy('studenci:uczelnie_lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['uczelnia'] = Uczelnia.objects.all()
        return context

    def form_valid(self, form):
        messages.success(self.request, "Dodano uczelnię!")
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class EdytujMiasto(SuccessMessageMixin, UpdateView):
    model = Miasto
    form_class= MiastoModelForm
    template_name = 'studenci/miasto_dodaj.html'
    success_url = reverse_lazy('studenci:miasta_lista')
    success_message = 'Zaktualizowano miasto!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['miasta'] = Miasto.objects.all()
        return context

class UsunMiasto(DeleteView):

    model = Miasto
    success_url = reverse_lazy('studenci:miasta_lista')
    success_message = 'Usunięto miasto!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['miasta'] = Miasto.objects.all()
        return context

@method_decorator(login_required, name='dispatch')
class EdytujUczelnia(SuccessMessageMixin, UpdateView):
    model = Uczelnia
    form_class= UczelniaForm
    template_name = 'studenci/uczelnia_dodaj.html'
    success_url = reverse_lazy('studenci:lista_uczelni')
    success_message = 'Zaktualizowano uczelnię!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['uczelnia'] = Uczelnia.objects.all()
        return context

class UsunUczelnia(DeleteView):

    model = Uczelnia
    success_url = reverse_lazy('studenci:lista_uczelni')
    success_message = 'Usunięto uczelnię!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['uczelnia'] = Uczelnia.objects.all()
        return context

studenci/templates/studenci/index.html
{% extends 'szablon.html' %}


{% block naglowek %}Studenci!{% endblock naglowek %}
{% block tresc %}
    <p> ;-)</p>
{% endblock tresc %}

studenci/templates/studenci/lista_uczelni.html
{% extends 'szablon.html' %}

{% block naglowek %}Uczelnia{% endblock naglowek %}

{% block tresc %}

<h2>Lista uczelni</h2>
<ol>
    {% for uczelnia in uczelnia %}
        <li>{{ uczelnia.nazwa }}
            <a href="{% url 'studenci:uczelnia_edytuj' miasto.id %}" class="btn-sm"> Edytuj </a>,
            <a href="{% url 'studenci:uczelnia_usun' miasto.id %}" class="btn-sm"> Usuń </a>
        </li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/login.html
{% extends 'szablon.html' %}

{% block naglowek %}Studenci_ Logowanie{% endblock naglowek %}

{% block tresc %}

<form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zapisz">
</form>

{% endblock tresc %}

studenci/templates/studenci/login2.html
{% extends 'szablon.html' %}

{% block naglowek %}Uczelnie logowanie{% endblock naglowek %}

{% block tresc %}

<form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zapisz">
</form>

{% endblock tresc %}

studenci/templates/studenci/miasta.html
{% extends 'szablon.html' %}

{% block naglowek %}Miasta{% endblock naglowek %}

{% block tresc %}
<h2>Dodaj miasto</h2>
    {% if user.is_authenticated %}
        {% if perms.studenci.add_miasto %}
            <form action="." method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Zapisz">
            </form>
        {% else %}
            <div class="well">Nie możesz dodawać miast!</div>
        {% endif %}
    {% endif %}
<h2>Lista miast</h2>
<ol>
    {% for miasto in miasta %}
        <li>{{ miasto.nazwa }}&nbsp;{{ miasto.kod }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/miasto_confirm_delete.html
{% extends 'szablon.html' %}

{% block naglowek %}Miasta{% endblock naglowek %}

{% block tresc %}

<h2>Usuwanie Miasta</h2>
    <form  method="POST">
        <p class="lead">CZy rzeczywiście chcesz usunąć maisto:<br>
            {{  object.nazwa }}, {{ object.kod }}?
        </p>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Usuń">
    </form>
{% endblock tresc %}

studenci/templates/studenci/miasto_dodaj.html
{% extends 'szablon.html' %}

{% block naglowek %}Miasta{% endblock naglowek %}

{% block tresc %}
    {% load crispy_forms_tags %}

<h2>Dodaj miasto</h2>

            <form  method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Zapisz">
            </form>

<h2>Lista miast</h2>
<ol>
    {% for miasto in miasta %}
        <li>{{ miasto.nazwa }}&nbsp;{{ miasto.kod }}
            <a href="{% url 'studenci:miasta_edytuj' miasto.id %}" class="btn-sm"> Edytuj </a>
        </li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/miasto_list.html
{% extends 'szablon.html' %}

{% block naglowek %}Miasta{% endblock naglowek %}

{% block tresc %}

<h2>Lista miast</h2>
<ol>
    {% for miasto in object_list %}
        <li>{{ miasto.nazwa }}&nbsp;{{ miasto.kod }}
            <a href="{% url 'studenci:miasta_edytuj' miasto.id %}" class="btn-sm"> Edytuj </a>,
            <a href="{% url 'studenci:miasta_usun' miasto.id %}" class="btn-sm"> Usuń </a>
        </li>

    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/uczelnia.html
{% extends 'szablon.html' %}

{% block naglowek %}Uczelnia{% endblock naglowek %}

{% block tresc %}
<h2>Dodaj uczelnię:</h2>
<form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
  <!--  <input type="text" name="nazwa" maxlength="30">
    <br>
    <input type="text" name="kod" maxlength="6">
    <br> -->
    <input type="submit" value="Zapisz">
</form>
<h2>Lista uczelni</h2>
<ol>
    {% for uczelnia in uczelnia %}
        <li>{{ uczelnia.nazwa }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/uczelnia_confirm_delete.html
{% extends 'szablon.html' %}

{% block naglowek %}Uczelnia{% endblock naglowek %}

{% block tresc %}

<h2>Usuwanie Uczelni</h2>
    <form  method="POST">
        <p class="lead">CZy rzeczywiście chcesz usunąć uczelnię:<br>
            {{  object.nazwa }}?
        </p>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Usuń">
    </form>
{% endblock tresc %}

studenci/templates/studenci/uczelnia_dodaj.html
{% extends 'szablon.html' %}

{% block naglowek %}Uczelnia{% endblock naglowek %}

{% block tresc %}
        {% load crispy_forms_tags %}

<h2>Dodaj uczelnię:</h2>
<form  method="POST">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Zapisz">
</form>
<h2>Lista uczelni</h2>
<ol>
    {% for uczelnia in uczelnia %}
        <li>{{ uczelnia.nazwa }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}