ankiety/urls.py
from django.urls import path
from . import views

app_name = 'ankiety'
urlpatterns = [
	path('', views.ListaPytan.as_view(), name='lista-pytan'),

]

djangoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('pizza/', include('pizza.urls')),
    path('studenci/', include('studenci.urls')),
    path('ankiety/', include('ankiety.urls')),
    path('admin/', admin.site.urls),
]

pizza/urls.py
from django.urls import path

from . import views
app_name = 'pizza'
urlpatterns = [
	path('', views.index, name='index'),
    path('news/', views.news, name='news'),
    path('skladnik/dodaj', views.SkladnikDodaj, name='skladnik_add'),

]

studenci/urls.py
from django.urls import path
from django.views.generic import ListView
from . import views
from studenci.models import Miasto

app_name = 'studenci'
urlpatterns = [
	path('', views.index, name='index'),
    path('miasta/lista', ListView.as_view(model=Miasto), name='miasta_lista'),
    path('news/', views.news, name='news'),
    path('miasta/', views.miasta, name='miasta'),
    path('miasta/dodaj', views.DodajMiasto.as_view(), name='miasta_dodaj'),
    path('miasta/edytuj/<int:pk>', views.EdytujMiasto.as_view(), name='miasta_edytuj'),
    path('miasta/usun/<int:pk>', views.UsunMiasto.as_view(), name='miasta_usun'),
    path('uczelnia/', views.uczelnia, name='uczelnia'),
    path('uczelnia/lista', views.ListaUczelni.as_view(), name='uczelnie_lista'),
    path('uczelnia/dodaj', views.DodajUczelnia.as_view(), name='uczelnia_dodaj'),
    path('uczelnia/edytuj/<int:pk>', views.EdytujUczelnia.as_view(), name='uczelnia_edytuj'),
    path('uczelnia/usun/<int:pk>', views.UsunUczelnia.as_view(), name='uczelnia_usun'),
    path('login/', views.login, name='login'),
    path('login2/', views.login2, name='login2'),

]

users/urls.py
from django.urls import path

from . import views
app_name = 'users'
urlpatterns = [
	path('', views.index, name='index'),
    path('rejestruj/', views.rejestruj, name='rejestruj'),
    path('loguj/', views.loguj, name='loguj'),
    path('wyloguj/', views.wyloguj, name='wyloguj'),

]

templates/szablon.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block tytul %}Aplikacja Django{% endblock tytul %}</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
 <nav class="navbar navbar-expand-sm bg-light">
        <a class="navbar-brand" href="http://lo1.sandomierz.pl">I LO CG</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
            <li class="nav-tem dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Studenci</a>
                <div class="dropdown-menu">
                    <a href="{% url 'studenci:index' %}" class="dropdom-item">Strona główna</a></br>
                    <a href="{% url 'studenci:miasta_lista' %}" class="dropdom-item">Lista miast</a></br>
                    <a href="{% url 'studenci:miasta_dodaj' %}" class="dropdom-item">Utwórz miasto</a></br>
                    <a href="{% url 'studenci:miasta' %}" class="dropdom-item">Miasta</a> </br>
                    <a href="{% url 'studenci:uczelnia' %}" class="dropdom-item">Uczelnie</a></br>
                    <a href="{% url 'studenci:uczelnie_lista' %}" class="dropdom-item">Lista Uczelni</a></br>
                    <a href="{% url 'studenci:uczelnia_dodaj' %}" class="dropdom-item">Utwórz uczelnię</a></br>
                    <a href="{% url 'studenci:login' %}" class="dropdom-item">Logowanie</a></br>


                </div>

            </li>
            <li class="nav-tem dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Pizza</a>
                <div class="dropdown-menu">
                    <a href="{% url 'pizza:index' %}" class="dropdom-item">Strona główna</a>
                    <a href="{% url 'pizza:news' %}" class="dropdom-item">Nowości</a>
                    <a href="{% url 'pizza:skladnik_add' %}" class="dropdom-item">Dodaj Składnik</a>

                </div>
            </li>
            <li class="nav-tem dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Ankiety</a>
                <div class="dropdown-menu">
                    <a href="{% url 'ankiety:lista-pytan' %}" class="dropdom-item">Strona główna</a>


                </div>
            </li>
            <li class="nav-tem dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Użytkownicy</a>
                <div class="dropdown-menu">
                    <a href="{% url 'users:index' %}" class="dropdom-item">Strona główna</a></br>
                    {% if not user.is_authenticated %}
                        <a href="{% url 'users:rejestruj' %}" class="dropdom-item">Rejestruj</a></br>
                        <a href="{% url 'users:loguj' %}" class="dropdom-item">Logowanie</a></br>
                    {% else %}
                         <a href="{% url 'users:wyloguj' %}" class="dropdom-item">Wyloguj</a></br>
                    {% endif %}
                </div>
            </li>

            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col">
            <h1>{% block naglowek %}Aplikacja Django{% endblock naglowek %}</h1>
    {% if messages %}
    <ul>
        {% for komunikat in messages %}
        <li>{{ komunikat }}</li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Brak komunikatów.</p>
    {% endif %}

{% block tresc %}{% endblock tresc %}
            </div>
            <div class="col"></div>
        </div>
    </div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>